from .separator import *
from .clock import *
from .battery import *
from .temperature import *
from .wifi import *
from .ram import *
from .cpugraph import *
from .volume import *
from .feed import *
from .ibus import *
from .mpd import *
